esphome:
  name: modo-tab-charger
  friendly_name: Modo Tab Charger
  name_add_mac_suffix: true
  project:
    name: modo.tab_charger
    version: dev
dashboard_import:
  package_import_url: github://mmodestas/modo-tab-charger/modo-tab-charger.yaml@main

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:
  ap:

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: ESPHome Version
    
switch:
  - platform: gpio
    pin: 4
    inverted: true
    name: "Charging"
    icon: "mdi:lightning-bolt-circle"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true 

bluetooth_proxy:
